# Generated by Django 4.0.4 on 2022-06-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0002_mascota_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(max_length=1, verbose_name='sexo'),
        ),
    ]
