# Generated by Django 4.0.4 on 2022-06-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0004_alter_mascota_esterilizado_alter_mascota_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id')),
                ('nombreP', models.CharField(max_length=50, verbose_name='nombre')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('cantidadInventario', models.IntegerField(default=0.0)),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
