# Generated by Django 4.0.4 on 2022-07-07 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0005_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fechaActualizado',
        ),
    ]
